stages:
    - build
    - release

variables:
    IMAGE_NAME: beenhamo/samba-server

image: carlallen/docker:buildx
before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker create context builder
    - docker buildx create builder --use

# Build the Docker image for multiple architectures
build:
    stage: build and release
    script:
        - VERSION=$(cat VERSION)
        - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest $IMAGE_NAME:$VERSION . --push
    only:
        - production
