stages:
    - build
    - release

# Cache Docker layers for faster builds
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .docker/

# Build the Docker image
build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
        - docker build -t "beenhamo/samba-server:latest" .
        - docker save -o .docker/image.tar "beenhamo/samba-server:latest"
    only:
        - branches

# Publish the Docker image on release
release:
    stage: release
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker load -i .docker/image.tar
        - docker tag "beenhamo/samba-server:latest" "beenhamo/samba-server:$CI_COMMIT_TAG"
        - docker push "beenhamo/samba-server:latest"
        - docker push "beenhamo/samba-server:$CI_COMMIT_TAG"
    only:
        - tags
