stages:
    - build
    - release

variables:
    IMAGE_NAME: beenhamo/samba-server

before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
    # - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker context create builder
    - docker buildx create builder --use

# Build the Docker image for multiple architectures
build:
    stage: build
    script:
        - VERSION=$(cat VERSION)
        - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$VERSION .
        - docker buildx imagetools create -t $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
# release:
#     stage: release
#     script:
#         - VERSION=$(cat VERSION)
#         - docker buildx build --load -t $IMAGE_NAME:latest .
#     only:
#         - production
