stages:
    - build
    - release

# Cache Docker layers for faster builds
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .docker/

# Build the Docker image
build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
        - docker build -t "$DOCKER_IMAGE_NAME:latest" .
        - docker save -o .docker/image.tar "$DOCKER_IMAGE_NAME:latest"
    only:
        - branches

# Publish the Docker image on release
release:
    stage: release
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker load -i .docker/image.tar
        - docker tag "$DOCKER_IMAGE_NAME:latest" "$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG"
        - docker push "$DOCKER_IMAGE_NAME:latest"
        - docker push "$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG"
    only:
        - tags
