stages:
    - build
    - release

variables:
    IMAGE_NAME: beenhamo/samba-server

image: carlallen/docker:buildx
before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker buildx create --name builder --use

# Build the Docker image for multiple architectures
build:
    stage: build
    script:
        - VERSION=$(cat VERSION)
        - echo "Building Docker image for $IMAGE_NAME:$VERSION"

        - docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
