stages:
    - build
    - release

variables:
    IMAGE_NAME: beenhamo/samba-server

before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"

# Build the Docker image
build:
    stage: build
    script:
        - VERSION=$(cat VERSION)
        - docker build -t $IMAGE_NAME:$VERSION .
        - docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

release:
    stage: release
    script:
        - VERSION=$(cat VERSION)
        - docker push $IMAGE_NAME:$VERSION
        - docker push $IMAGE_NAME:latest
    only:
        - production
