services:
    smb:
        build: .
        container_name: samba-server
        network_mode: host
        volumes:
            - ./data:/srv/samba/share
        environment:
            - SAMBA_USER=devuser
            - SAMBA_PASSWORD=password
            - SAMBA_SHARE=share
        restart: unless-stopped
