services:
    smb:
        image: beenhamo/samba-server:latest
        container_name: samba-server
        network_mode: host
        volumes:
            - ./data:/srv/samba/share
        environment:
            - SAMBA_USER=smbuser
            - SAMBA_PASSWORD=password
            - SAMBA_SHARE_NAME=share
        restart: unless-stopped
